server:
  port: 8001

spring:
  datasource:
    druid:
      url: jdbc:mysql://8.129.131.201:3306/bookshop?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
      username: root
      password: Doplove52)
      driver-class-name: com.mysql.cj.jdbc.Driver